name: BotFolder
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: randalstevens <email@example.com>

environment:
  sdk: '>=1.8.1 <2.0.0'

dependencies:
  oauth: '^0.4.0'
  twitter: '^0.5.1'
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0

web:
  compiler:
    debug: dartdevc
